[2024-01-05T15:16:02.259+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2 permission to 509
[2024-01-05T15:16:02.260+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2'
[2024-01-05T15:16:02.294+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2 permission to 509
[2024-01-05T15:16:02.295+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2'
[2024-01-05T15:16:02.337+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.TaskId2 scheduled__2024-01-05T15:15:00+00:00 [queued]>
[2024-01-05T15:16:02.347+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.TaskId2 scheduled__2024-01-05T15:15:00+00:00 [queued]>
[2024-01-05T15:16:02.348+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-05T15:16:02.363+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): TaskId2> on 2024-01-05 15:15:00+00:00
[2024-01-05T15:16:02.367+0000] {standard_task_runner.py:60} INFO - Started process 297 to run task
[2024-01-05T15:16:02.371+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'TaskId2', 'scheduled__2024-01-05T15:15:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmphwu2cbs0']
[2024-01-05T15:16:02.375+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask TaskId2
[2024-01-05T15:16:02.437+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2 permission to 509
[2024-01-05T15:16:02.438+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T15:15:00+00:00/task_id=TaskId2'
[2024-01-05T15:16:02.440+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.TaskId2 scheduled__2024-01-05T15:15:00+00:00 [running]> on host 335d4f10cd51
[2024-01-05T15:16:02.527+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='TaskId2' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T15:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T15:15:00+00:00'
[2024-01-05T15:16:02.529+0000] {logging_mixin.py:188} INFO - Table created
[2024-01-05T15:16:02.529+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-05T15:16:02.539+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=TaskId2, execution_date=20240105T151500, start_date=20240105T151602, end_date=20240105T151602
[2024-01-05T15:16:02.584+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T15:16:02.607+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
