[2024-01-05T11:17:01.243+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1 permission to 509
[2024-01-05T11:17:01.243+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1'
[2024-01-05T11:17:01.272+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1 permission to 509
[2024-01-05T11:17:01.272+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1'
[2024-01-05T11:17:01.308+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.TaskId1 scheduled__2024-01-05T11:16:00+00:00 [queued]>
[2024-01-05T11:17:01.319+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.TaskId1 scheduled__2024-01-05T11:16:00+00:00 [queued]>
[2024-01-05T11:17:01.320+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-05T11:17:01.335+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): TaskId1> on 2024-01-05 11:16:00+00:00
[2024-01-05T11:17:01.341+0000] {standard_task_runner.py:60} INFO - Started process 5449 to run task
[2024-01-05T11:17:01.345+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'TaskId1', 'scheduled__2024-01-05T11:16:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmpsqnhi7ge']
[2024-01-05T11:17:01.348+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask TaskId1
[2024-01-05T11:17:01.402+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1 permission to 509
[2024-01-05T11:17:01.404+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T11:16:00+00:00/task_id=TaskId1'
[2024-01-05T11:17:01.405+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.TaskId1 scheduled__2024-01-05T11:16:00+00:00 [running]> on host 9d30878c4ef0
[2024-01-05T11:17:01.507+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='TaskId1' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T11:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T11:16:00+00:00'
[2024-01-05T11:17:01.510+0000] {logging_mixin.py:188} INFO - ZAEBALLL11
[2024-01-05T11:17:01.511+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-05T11:17:01.523+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=TaskId1, execution_date=20240105T111600, start_date=20240105T111701, end_date=20240105T111701
[2024-01-05T11:17:01.557+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T11:17:01.584+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
